# config/packages/prod/doctrine.yaml
doctrine:
    dbal:
        # null driver = no real connection during cache:clear
        url: 'env(resolve:DATABASE_URL):'
        # keep the rest of your settings (charset, server-version, …)
    orm:
        auto_generate_proxy_classes: false
        proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool